language: python  
python:
    - 3.6.3

branches:
    only:
        - source
        - master

before_install:
    - git clone --branch=source https://github.com/$GITHUB_USER/$GITHUB_REPO_NAME
    - cd $(basename ${GITHUB_REPO_NAME%.git})

install:
    - sudo locale-gen zh_CN.UTF-8
    - sudo locale-gen en_US.UTF-8
    - pip install -r requirements.txt

script:  
    - mkdir output
    - env SITEURL="$GITHUB_REPO_NAME" make html

after_success:
    - cd output
    - git add -A .
    - git commit -m ":blush: Update from travis."
    - git push -f -q https://GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO_NAME master
