language: python  
python:
    - 3.6.3
cache: pip

install:
    - sudo locale-gen zh_CN.UTF-8
    - sudo locale-gen en_US.UTF-8
    - pip install --upgrade pip
    - pip install -r requirements.txt

script:  
    - mkdir output
    - make gen_issue token $GITHUB_TOKEN
    - env SITEURL="$GITHUB_REPO_NAME" make html

after_success:
    - cd output
    - git add -A .
    - git commit -m ":blush: Update from travis."
    - git push -f -q https://GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO_NAME master

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    target_branch: master
    on:
        branch: source
