language: python  
python:
    - 3.6.3

branches:
    only:
        - master

install:
    - sudo locale-gen zh_CN.UTF-8
    - sudo locale-gen en_US.UTF-8
    - pip install -r requirements.txt
    - mkdir output

script:  
    - env SITEURL="paxinla.github.io" make html

after_success:
    - cd output
    - git add -A .
    - git commit -m ":blush: Update from travis."
    - git push -f -q https://paxinla:$GITHUB_TOKEN@github.com/paxinla/paxinla.github.io
